kafka:
  bootstrap-servers: localhost:9092
  schema-registry:
    url: http://localhost:8081
  producer:
    parking-events-topic: parking-events-proto
    occupancy-topic: parking-occupancy-by-zone

simulation:
  total-events: 1000
  entry-probability: 0.6
  delay: 1000
  initial-occupancy: 0.3
  time-of-day:
    enabled: true
    start-hour: 6
    end-hour: 22
  event-rate:
    peak-rate: 10
    off-peak-rate: 2
    peak-hours: [8, 17]