kafka:
  bootstrap-servers: localhost:9092
  schema-registry:
    url: http://localhost:8081
  producer:
    topic: parking-events-proto

simulation:
  total-events: 100
  entry-probability: 0.6
  delay: 1000
  time-of-day:
    enabled: true
    start-hour: 6
    end-hour: 22
  event-rate:
    peak-rate: 10
    off-peak-rate: 2
    peak-hours: [8, 17]
  initial-occupancy: 0.3 